name: sarscov2
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    - python=3.9
    - bioconda::ivar=1.3
    - bioconda::bcftools=1.10.2
    - bioconda::bwa=0.7.17
    - bioconda::sambamba=0.8.0
    - bioconda::freebayes=1.3.5
    - bioconda::seqtk=1.3
    - conda-forge::nodejs=15.14.0